server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # SPA fallback
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy API publique vers le service api
    location /public/ {
        proxy_pass         http://api:3000/public/;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_cache_valid  200 1m;
        add_header         Cache-Control "public, max-age=60";
    }

    # Compression
    gzip on;
    gzip_types text/plain text/css application/javascript application/json application/atom+xml;
    gzip_min_length 1024;

    # Headers sécurité
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";
    add_header Referrer-Policy "strict-origin-when-cross-origin";
}
